[theme]
theme = "bad-wolf"

[icons]
icons = "awesome6"

[icons.overrides]
memory_mem = "ğŸ¤¯"
cpu = "âš™ï¸ "
cogs = "ğŸš›"
net_wired = ""
net_up = "â¬†ï¸"
net_down = "â¬‡ï¸"
music_next = "ï”"
time = ""
music_play = "ï‹"

# [[block]]
# block = "music"
# marquee = true
# player = "spotify"
# buttons = ["play", "next"]
# format = "{artist} - {title}"

[[block]]
block = "net"
# format = "$icon {speed_up;K} {speed_down;K}"

[[block]]
block = "custom"
command = ''' echo "â˜€ï¸  $(senec --address 192.168.2.190 --kilo produced)" kW '''
interval = 5

[[block]]
block = "custom"
command = ''' echo "ğŸ”¥ $(senec --address 192.168.2.190 --kilo consumed)" kW '''
interval = 5

[[block]]
block = "custom"
command = ''' echo "ğŸ”‹ $(senec --address 192.168.2.190 --kilo battery) kW / $(senec --address 192.168.2.190 battery-percentage) %"'''
interval = 5


[[block]]
block = "memory"
# display_type = "memory"
format = "$icon $mem_used_percents"
format_alt = "$icon $swap_used_percents"
interval = 15

[[block]]
block = "cpu"
interval = 1


[[block]]
block = "load"
interval = 1
format = "$icon $1m.eng(w:4)"

# [[block]]
# block = "sound"

[[block]]
block = "time"
interval = 10
format = " $icon $timestamp.datetime(f:'%a %d/%m %R') "

